name: Testing upload-artifacts 2

on:
  workflow_dispatch:
env:
  CONTAINER: andrewdavidsmith/transferase-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start the container
        run: |
          docker pull $CONTAINER
          docker run --name build-container \
          -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null
      - name: build the binary
        env:
          SCRIPT: |
            cd /workspace
            gcc main.c
            ls -lR
        run: |
          docker exec build-container bash -c "$SCRIPT"
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload the a.out
        uses: actions/upload-artifact@v4
        with:
          name: a-dot-out
          path: a.out
