name: Testing upload-artifacts 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-build
    steps:
      - name: Start the container
        uses: actions/checkout@v4
        run: |
          docker pull $CONTAINER
          docker run --name build-container \
          -d -v ${{ github.workspace }}:/workspace $CONTAINER tail -f /dev/null
      - name: build the binary
        env:
          SCRIPT: |
            cd /workspace
            gcc main.c
        run: |
          docker exec build-container bash -c "$SCRIPT"
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload the a.out
        uses: actions/upload-artifact@v4
        with:
          name: a-dot-out
          path: a.out
