name: Testing download-artifacts

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest
    steps:
    - name: Get run ID of "Testing upload-artifacts" workflow
      id: get-run-id
      run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="Testing upload-artifacts"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow "${WF_NAME}" --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
    - name: Download?
      uses: actions/download-artifact@v4
      with:
        name: a-dot-out
        # repository: andrewdavidsmith/upload-test
        run-id: ${{ steps.get-run-id.outputs.run-id }}
    - name: Do something
      run: |
        ls -lR
        ./a.out
