name: Test ncurses on macOS

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: |
        brew update
        brew install ncurses
    - name: Configure
      run: |
        # brew --prefix
        # ls -lR /usr/local/opt/ncurses
        # ls -lR /usr/local/Cellar/ncurses/6.5
        # find /usr/local/opt -name \*ncurses\*
        NCURSES_DIR=$(brew --prefix ncurses)
        echo ${NCURSES_DIR}
        export NCURSES_LIB_DIR=/usr/local/opt/ncurses/lib
        export NCURSES_INCLUDE_DIR=/usr/local/opt/ncurses/include
        gcc-14 main.c ${NCURSES_LIB_DIR}/libncurses.a -I${NCURSES_INCLUDE_DIR}
    - name: Upload the a.out
      uses: actions/upload-artifact@v4
      with:
        name: a-dot-out
        path: a.out
