name: Testing download-artifacts 2

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest
    container: andrewdavidsmith/transferase-build
    steps:
    - name: Get run ID of "Testing upload-artifacts" workflow
      id: get-run-id
      run: |
          echo "asdf=1234" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Do something
      run: |
        echo ${{ steps.get-run-id.outputs.asdf }}
