name: Test ncurses on macOS

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: brew update
    - name: Install dependencies
      run: |
        brew install ncurses
        brew link ncurses
    - name: Configure
      run: |
        brew --prefix
        find /usr/local/opt/ncurses
        gcc-14 main.c -L/usr/local/opt/ncurses/lib -I/usr/local/opt/ncurses/include
        a.out
