name: Testing download-artifacts

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest
    steps:
    - name: Download?
      uses: actions/download-artifact@v4
      with:
        name: a-dot-out
        # repository: andrewdavidsmith/upload-test
        # run-id: 1234
    - name: Do something
      run: |
        ls -lR
        ./a.out
