name: Test ncurses on macOS

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: brew update
    - name: Install dependencies
      run: |
        brew install ncurses
    - name: Configure
      run: |
        brew --prefix
        sudo find /usr -name libncurses.a
        sudo find /opt -name libncurses.a
        sudo find /usr -name ncurses.h
        sudo find /opt -name ncurses.h
        gcc-14 main.c -I/usr/local/Cellar/ncurses/6.5/include -L/usr/local/Cellar/ncurses/6.5/lib
        a.out
