name: Testing download-artifacts

on:
  workflow_dispatch:

jobs:
  download-test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Download?
      uses: actions/download-artifact@v4
      with:
        name: a-dot-out
        # repository: andrewdavidsmith/upload-test
        # run-id: 1234
    - name: Do something
      run: |
        ls -lR
        ./a.out
