name: Test ncurses on macOS

on:
  workflow_dispatch:

jobs:
  macos-test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Update Homebrew
      run: |
        brew update
        brew install ncurses
    - name: Configure
      run: |
        brew --prefix
        ls -lR /usr/local/opt/ncurses
        ls -lR /usr/local/Cellar/ncurses/6.5
        # find /usr/local/opt -name \*ncurses\*
        # cc main.c -L/usr/local/opt/ncurses/lib -I/usr/local/opt/ncurses/include
        # a.out
