name: Platforms

on:
  workflow_dispatch:

jobs:
  macos-platforms:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Platforms
      run: |
        pip install packaging
        python -c "import packaging.tags; print(next(packaging.tags.platform_tags()))"
